### ISSUE TITLE
Unable to explore/find devices

### ISSUE THREAD

**Issue by Maxime01200** [ankohanse/hass-studer-xcom#10]
I am trying to install the integration, config of the moxa OK, integration finds it, good port, but finish with an error when finding device... 

Enregistreur: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
S'est produit pour la première fois: 22:58:03 (4 occurrences)
Dernier enregistrement: 22:58:36

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 215, in get
    return await super().get(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 108, in get
    result = await self._flow_mgr.async_configure(flow_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/studer_xcom/config_flow.py", line 459, in async_step_numbers
    datapoint: XcomDatapoint = self._dataset.getByNr(nr, family.idForNr)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioxcom/xcom_datapoints.py", line 146, in getByNr
    raise XcomDatapointUnknownException(nr, family_id)
aioxcom.xcom_datapoints.XcomDatapointUnknownException: (11042, 'vt')

**Desktop :**
OS: iMac 2011 MacOS 10.13.6, same on Windows
Browser Brave

**HA versions**
HA Core 2024.11.2
Supervisor 2024.11.2
Operating System 13.2
Interface utilisateur 20241106.2

**Comment by ankohanse** [comment]
Thanks for reporting this!

I have identified the source of the problem: once the devices have been detected, it tries to add default infos and params as Home Assistant entities. It had VT 11042 listed as default for VarioTrack devices, but that params number does not exist!
Now corrected the default numbers used for the VarioTrack, which should solve the issue.
Will release this fix as version 2024.11.3 today.

Let me know if you encounter other issues, I do not have a VarioTrack myself, so have not been able to do testing on that device.

**Comment by Maxime01200** [comment]
Works fine, evrything is discovered !
XTM 4000, VT1, VT2, BMS discovered and data received.
Thank you very much
Maxime

**Comment by JeffersM1** [comment]
I have the setting shown in this screen shot.  I believe that they are the standard Studer settings.  

<img width="1597" height="123" alt="Image" src="https://github.com/user-attachments/assets/57db959b-6e13-4073-ba59-53c52640422e" />

**Comment by ankohanse** [comment]
Mine are exactly the same as @JeffersM1:

<img width="1049" height="127" alt="Image" src="https://github.com/user-attachments/assets/d04fa6d6-15f3-4dd9-92ee-f30a25378c0a" />
